# config/_default/config.toml
baseURL = "https://chikuang.github.io/"
publishDir = "../chikuang.github.io"
languageCode = "en-us"
title = "Chi-Kuang Yeh/葉啟光"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout = 3000
enableGitInfo = true

# Enable menu merging from menus.toml
[menus]

# Enable parameter merging from params/*.toml
[params]