[params]
subtitle= "PhD"
interests = """I possess a wide range of interests, but for now, my research 
  is centred around: 
  1. Functional data analysis.
  2. Statistical machine learning and high-dimensional statistical inference.
  3. Dependence modeling.
  4. Optimal design of experiment.
  5. Applications include drug development, toxicology, neuroscience, to only name a few.
  """
cv_name= "CV_YCK_Nov3_24.pdf"
# blog="https://uwaterloo.ca/scholar/c26yeh/home"
# site="https://uwaterloo.ca/scholar/c26yeh/home"

[[params.affilation]]
name = "McGill University & University of Waterloo"
position = "Postdoctoral Scholar"
contact = "chi-kuang.yeh@mail.mcgill.ca, chi-kuang.yeh@uwaterloo.ca"

[[params.introduction.paragraph]]
text = """Hello/你好! I am currently a postdoctoral scholar in the 
  [Department of Mathematics and Statistics](https://www.mcgill.ca/mathstat/) at 
  [McGill University](https://www.mcgill.ca/) jointly with the 
  [Department of Statisitcs and Actuarial Science](https://uwaterloo.ca/statistics-and-actuarial-science/)
  at the [University of Waterloo](https://uwaterloo.ca), kindly sponsored by the [Canadian Statistical Sciences Institute](https://canssi.ca/) (CANSSI). I am also affiliated with [Mila](https://mila.quebec/en) and UW's [Health Data Science Lab](https://uwaterloo.ca/health-data-science-lab/).
  I was originally from Hsinchu (新竹) and Taipei (台北), Taiwan, 
  and I lived in BC, Canada, for 12 years.
"""
[[params.introduction.paragraph]]
text= """My office is: Room 1216 on the top floor in [Burnside Hall](https://en.wikipedia.org/wiki/Burnside_Hall)."""

[[params.introduction.paragraph]]
text= """
  **Computing**:
  For those who want to use the MFCF server at UWaterloo, you may find the guidiance below useful. Feel free to contact me if you have any questions.
  + [Guideline to run R on MFCF server](https://chikuang.github.io/post/computing). """