[params]
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/chikuang"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/chi-kuang-yeh-040523110/"

[[params.social]]
name = "Researchgate"
icon = "user"
url = "https://www.researchgate.net/profile/Chi_Kuang_Yeh"

[[params.social]]
name = "googleScholar"
icon = "book"
url = "https://scholar.google.ca/citations?user=_v_Vy1sAAAAJ&hl=en"