[params]
[[params.softwares]] 
[[params.softwares.software]]
name = "FTSgof"
authors = "Mihyun Kim, **Chi-Kuang Yeh**, Yuqian Zhao & Gregory Rice"
description  = """A R package for white noise and goodness-of-fit tests for functional time series"""
software_page = ""
paper = ""
cran = "https://cran.r-project.org/web/packages/FTSgof/index.html"
link = ""
just_link = ""
code_link = ""
github_link = "https://github.com/veritasmih/FTSgof"
[[params.softwares.software]]
name = "evalRTPF"
authors = "**Chi-Kuang Yeh**, Gregory Rice & Joel Dubin"
description  = """A R package to  Evaluating the probabilistic 
	  forecasts between competitive forecasters """
software_page = ""
paper = ""
link = ""
just_link = ""
code_link = ""
github_link = "https://github.com/chikuang/evalRTPF"
[[params.softwares.software]]
name = "optDesign"
authors = "**Chi-Kuang Yeh** & Julie Zhou"
description  = """A MATLAB toolbox to compute optimal regression design """
software_page = ""
link = ""
just_link = ""
code_link = ""
github_link = "https://github.com/chikuang/optDesign"
[[params.softwares.software]]
name = "SLSEdesign"
authors = "**Chi-Kuang Yeh**, Julie Zhou & Jason Hou-Liu" 
description  = """A R package for computing optimal regression designs under the second-order least-squares estimator"""
software_page = ""
cran = "https://cran.rstudio.com/web/packages/SLSEdesign/index.html"
link = ""
just_link = ""
code_link = ""
github_link = "https://github.com/chikuang/SLSEdesign"
[[params.softwares.software]]
name = "yehUtil"
authors = "**Chi-Kuang Yeh**"
description  = """A R package for knitting some RMarkdown reports and other usages"""
software_page = ""
link = ""
just_link = ""
code_link = ""
github_link = "https://github.com/chikuang/yehUtil"