[params]
[[params.teaching]]
year = "Direct Study"
[[params.teaching.course]]
name = "Introduction to Cross-Validation"
link = "https://chikuang.github.io/course/directstudy"

[[params.teaching]]
year = "2025 Fall"
[[params.teaching.course]]
name = "Computational Methods in Statistics"
[[params.teaching]]
year = "2024"
[[params.teaching.course]]
name = "STAT 230 – Introduction to Probability"
# description = "Co-taught with [Erik Hintz](https://uwaterloo.ca/scholar/ehintz), [Jeffery Negrea](https://utstat.toronto.edu/~negrea/) and [Justin Ko](https://justinpko.github.io/). ."
link = "https://chikuang.github.io/course/stat230"

# [[params.projects.project]]
#		name = "Integer eget aliquet nibh praesent tristique magna"
#		description  = ""
#		project_page = "https://myprojecthomepage.com"
#		code_link = ""
#		blog_link = "https://ablogpost.com"

#[[params.publications]]
#  year="Preprint"

#  [[params.publications.paper]]
#    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
#    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
#    dest  = "Helga Zita Journal"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#    name = "In cursus turpis massa tincidunt dui ut ornare lectus sit"
#    authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
#    dest  = "Meklit Katlego Conference"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"



#  [[params.publications.paper]]
#		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
#		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
#		dest  = "Zorka Vita Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
#		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
#		dest  = "Lena Randa Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = ""

#  [[params.publications.paper]]
#		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
#		authors = "__Hadi Sinaee__, Caroll Comes"
#		dest  = "Thandeka Radhika Conference"
#		link = ""
#		code_link = ""
#		blog_link = ""
